### PR TITLE
python MutableMapping version incompat fix

### PR DESCRIPTION
**Pull request by DHMike57**
MutableMapping has been moved to collections.abc for version 3.10

### CODE REVIEW

**Comment by damerell** [comment]
Thanks for the PR. Vanilla seems to have done something similar as part of their commit https://github.com/crawl/crawl/commit/eca56f19eff3a9a16c8721e4eae3363280a8c078 - although not picking 3.10 specifically, and I see it's been deprecated since 3.3. I don't really know much Python - do you think we should just pull in their commit, please?

**Comment by DHMike57** [comment]
I don't know much about python either, as you can see from my slightly non-idiomatic fix!  It's a bit confusing, but from what I found it looks like `MutableMapping` was moved into `collections.abc` at the beginning of version 3, but an alias was left in `collections` that has been removed in version 3.10 which is the first version that breaks (which is what I have - latest arch).  I haven't got any earlier versions to try out. I **think** the deprecation in 3.3 was a warning of the upcoming incompatibility, and that `collections.abc.MutableMapping` is here to stay.  If it were me, I'd use vanilla's patch - unlike me they are proper programmers :)

Many thanks for maintaining your fork - enjoying it greatly so far!

Mike

**Comment by damerell** [comment]
I've just pushed a new version with the equivalent vanilla commit. I presume you have a computer with a really new Python and as such I'd be grateful if you could confirm it works OK there.

**Comment by DHMike57** [comment]
Just cloned a fresh copy and it  compiled fine with python3.10.10 (up to date Arch linux).  Thanks for the fix.

Mike

**Comment by damerell** [comment]
I'm closing this since you and one of the other Stoat Soupies both confirm it compiles now with vanilla's fix. Thanks for bringing it to our attention.

**Pull request closed without merging**
